#  MIT License
#
#  Copyright (c) 2022 anatawa12
#  Copyright (c) 2022 bd_
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.


name: GameCI

on:
  push:
    branches: [main, dev]
  # This is a bit of a radioactive event; we need to be very careful with what permissions
  # we assign this action, as we're allowing arbitrary code execution with the context of
  # whatever permissions we assign.
  pull_request_target: {}
  workflow_dispatch: {}
  workflow_call:
    secrets:
      UNITY_LICENSE:
        required: true

# pull_request_target grants access to a privileged GITHUB_TOKEN by default, revoke this
permissions: {}

jobs:
  build-and-test:
    strategy:
      matrix:
        #unity_version: [ auto, 2022.3.5f1 ]
        unity_version: [ auto ]
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: |
          mkdir .github/ProjectRoot/Packages/nadena.dev.ndmf -p
          mv [^P]* .github/ProjectRoot/Packages/nadena.dev.ndmf
          mv .github/ProjectRoot/* .
          mv 'Packages/nadena.dev.ndmf/UnitTests~' 'Packages/nadena.dev.ndmf/UnitTests'

      - uses: anatawa12/sh-actions/resolve-vpm-packages@master

      - run: |
          ls -lR
      - run: |
          ls -lR Packages/nadena*

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.unity_version }}
          restore-keys: Library-

      - uses: game-ci/unity-test-runner@v3
        id: gameci
        continue-on-error: ${{ matrix.unity_version != 'auto' }}
        env:
          # meh, just a personal license...
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          testMode: EditMode
          unityVersion: ${{ matrix.unity_version }}
          githubToken: ${{ github.token }}
          coverageOptions: generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+nadena.dev.*
          customParameters: -nographics -assemblyNames nadena.dev.ndmf.UnitTests

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test results
          path: ${{ steps.gameci.outputs.artifactsPath }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Coverage results
          path: ${{ steps.gameci.outputs.coveragePath }}